package coreExamples.throwExceptionTest;

method main() {
	throw new Exception { val message = "It worked!"; };
}